import {
  Banknote,
  ArrowLeftRight,
  Book,
  Bus,
  Car,
  CirclePlus,
  Circle,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Ellipsis,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  House,
  Laptop,
  Landmark,
  Music,
  PiggyBank,
  Pizza,
  Plane,
  PlugZap,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Store,
  Utensils,
  Wallet,
  Wifi,
  type LucideIcon,
} from 'lucide-react';

/** Mapa de nombre (kebab-case, guardado en BD) -> componente de icono. */
export const ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  'shopping-cart': ShoppingCart,
  bus: Bus,
  fuel: Fuel,
  house: House,
  'plug-zap': PlugZap,
  clapperboard: Clapperboard,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  landmark: Landmark,
  ellipsis: Ellipsis,
  wallet: Wallet,
  laptop: Laptop,
  store: Store,
  gift: Gift,
  'circle-plus': CirclePlus,
  circle: Circle,
  coffee: Coffee,
  plane: Plane,
  dumbbell: Dumbbell,
  wifi: Wifi,
  'piggy-bank': PiggyBank,
  banknote: Banknote,
  'arrow-left-right': ArrowLeftRight,
  car: Car,
  pizza: Pizza,
  shirt: Shirt,
  heart: Heart,
  book: Book,
  music: Music,
  gamepad2: Gamepad2,
};

/** Opciones disponibles para el selector de icono. */
export const ICON_OPTIONS = Object.keys(ICON_MAP);

/** Colores sugeridos para categorías. */
export const COLOR_OPTIONS = [
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#eab308',
  '#84cc16',
  '#10b981',
  '#06b6d4',
  '#0ea5e9',
  '#2563eb',
  '#6366f1',
  '#8b5cf6',
  '#a855f7',
  '#ec4899',
  '#f43f5e',
  '#059669',
  '#64748b',
];

export function getIconComponent(name: string): LucideIcon {
  return ICON_MAP[name] ?? Circle;
}
